experiment_dir: /results
n_forward_steps: 40
forward_steps_in_memory: 40
checkpoint_path: /ckpt.tar
logging:
  log_to_screen: true
  log_to_wandb: true
  log_to_file: true
  project: annak-downscaling
  entity: ai2cm
forcing_loader:
  dataset:
    data_path: /climate-default/2024-06-20-era5-1deg-8layer-1940-2022-netcdfs
  num_data_workers: 16
initial_condition:
  path: 2024-06-20-era5-1deg-8layer-1940-2022-netcdfs/1940010100.nc
  start_indices:
    times:
      - '1940-01-01T12:00:00'
data_writer:
  save_prediction_files: false
  save_monthly_files: false
  subselection:
    -
      label: ace_output
      names:
        - PRATEsfc
        - UGRD10m
        - VGRD10m
      time_selection:
        start: 0
        stop: 24

