experiment_dir: /eval
n_samples: 2
model:
  checkpoint_path: /checkpoints/best.ckpt
data:
  fine:
    - data_path: gs://vcm-ml-intermediate/2025-03-10-downscaling-2yr-XSHiELD
      engine: zarr
      file_pattern: 3km.zarr
      subset:
        interval_length: 1d
        start: 6d
        block_length: 7d
  coarse:
    - data_path: gs://vcm-ml-intermediate/2025-03-10-downscaling-2yr-XSHiELD
      engine: zarr
      file_pattern: 25km.zarr
      subset:
        interval_length: 1d
        start: 6d
        block_length: 7d
  lat_extent:
    start: 29.0
    stop: 45.0
  lon_extent:
    start: 232.0
    stop: 248.0
  batch_size: 32
  num_data_workers: 2
  strict_ensemble: False
events:
  - name: california-ar
    date: 2020-12-02T00:00
    lat_extent:
      start: 29.0
      stop: 45.0
    lon_extent:
      start: 232.0
      stop: 248.0
  - name: california-low
    date: 2021-12-15T12:00
    lat_extent:
      start: 29.0
      stop: 45.0
    lon_extent:
      start: 232.0
      stop: 248.0
logging:
  log_to_screen: true
  log_to_wandb: true
  log_to_file: true
  project: andrep-downscaling
  entity: ai2cm
