model:
  out_names:
  - PRATEsfc
  in_names:
  - PRATEsfc
  - eastward_wind_at_ten_meters
  - northward_wind_at_ten_meters
  loss:
    type: MSE
  module:
    config:
      model_channels: 128
      attn_resolutions: []
      num_blocks: 1
      channel_mult_emb: 6
      channel_mult:
      - 1
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
    type: unet_diffusion_song
  normalization:
    coarse:
      global_means_path: /climate-default/2025-09-25-downscaling-data-X-SHiELD-AMIP-downscaling/stats/100km/centering.nc
      global_stds_path: /climate-default/2025-09-25-downscaling-data-X-SHiELD-AMIP-downscaling/stats/100km/scaling-full-field.nc
    fine:
      global_means_path: /climate-default/2025-09-25-downscaling-data-X-SHiELD-AMIP-downscaling/stats/3km/centering.nc
      global_stds_path: /climate-default/2025-09-25-downscaling-data-X-SHiELD-AMIP-downscaling/stats/3km/scaling-full-field.nc
  num_diffusion_generation_steps: 18
  churn: 0.0
  p_mean: -1.2
  p_std: 1.8
  predict_residual: true
  sigma_max: 150.0
  sigma_min: 0.002
  use_fine_topography: true
optimization:
  lr: 0.0001
  optimizer_type: Adam
ema:
  decay: 0.999
validate_using_ema: true
train_data:
  sample_with_replacement: 160
  batch_size: 24
  num_data_workers: 4
  fine:
  - data_path: /climate-default/2025-09-25-downscaling-data-X-SHiELD-AMIP-downscaling
    file_pattern: 3km.zarr
    engine: zarr
    subset:
      start_time: '2014-01-01T00:00:00'
      stop_time: '2022-12-31T23:59:00'
  coarse:
  - data_path: /climate-default/2025-09-25-downscaling-data-X-SHiELD-AMIP-downscaling
    file_pattern: 100km.zarr
    engine: zarr
    subset:
      start_time: '2014-01-01T00:00:00'
      stop_time: '2022-12-31T23:59:00'
  lat_extent:
    start: -66.0
    stop: 70.0
  strict_ensemble: false
validation_data:
  batch_size: 76
  num_data_workers: 4
  fine:
  - data_path: /climate-default/2025-09-25-downscaling-data-X-SHiELD-AMIP-downscaling
    engine: zarr
    file_pattern: 3km.zarr
    subset:
      start_time: '2023-01-01T00:00:00'
      stop_time: '2024-01-01T00:00:00'
      step: 19
  coarse:
  - data_path: /climate-default/2025-09-25-downscaling-data-X-SHiELD-AMIP-downscaling
    engine: zarr
    file_pattern: 100km.zarr
    subset:
      start_time: '2023-01-01T00:00:00'
      stop_time: '2024-01-01T00:00:00'
      step: 19
  lat_extent:
    start: -66.0
    stop: 70.0
  strict_ensemble: false
coarse_patch_extent_lat: 16
coarse_patch_extent_lon: 16
max_epochs: 1500
validate_interval: 10
experiment_dir: /results
save_checkpoints: true
logging:
  project: andrep-downscaling
  entity: ai2cm
  log_to_wandb: true
generate_n_samples: 2
