coupled_ts:
  how: interpolate_sst
coupled_sea_ice:
  sst_threshold: 291.75
  extra_masked_names: ["sea_ice_volume"]
output_name_prefix: e3smv3-piControl-100yr-coupled
output_directory: /climate-default
atmosphere_fields:
  surface_temperature_name: TS
ocean:
  zarr_path: /climate-default/2025-06-11-E3SM-piControl-ocean-ice-19-levs-fix-mask.zarr
  time_chunk_size: 25
  timedelta: 5D
  extra_names_and_prefixes: ["idepth_", "mask_"]
atmosphere:
  zarr_path: /climate-default/2025-06-13-E3SMv3-coupled-piControl-atmosphere-data.zarr
  time_chunk_size: 500
  timedelta: 6h
  extra_names_and_prefixes: ["ak_", "bk_"]
output_writer:
  n_dask_workers: 64
