# config for creating surface temperature and fractions dataset for coupled
# training after uncoupled atmopshere pretraining with sst_from_ts

coupled_ts:
  how: interpolate_sst
coupled_sea_ice:
  sst_threshold: 291.75
  extra_masked_names: ["HI", "sea_ice_volume"]
output_name_prefix: cm4-piControl-200yr-coupled
version: "2025-08-22"
output_directory: /climate-default
atmosphere_timedelta: 6h
ocean:
  zarr_path: /climate-default/2025-08-07-cm4-piControl-200yr-ocean.zarr
  time_chunk_size: 25
  extra_names_and_prefixes: ["idepth_", "mask_"]
sea_ice:
  zarr_path: /climate-default/2025-08-22-cm4-piControl-200yr-sic-6h-to-5Davg.zarr
  time_chunk_size: 25
atmosphere:
  zarr_path: /climate-default/2025-03-21-CM4-piControl-atmosphere-land-1deg-8layer-200yr.zarr
  time_chunk_size: 500
  extra_names_and_prefixes: ["ak_", "bk_"]
output_writer:
  n_dask_workers: 64
