experiment_dir: /results
n_forward_steps: 7300
forward_steps_in_memory: 10
checkpoint_path: /ckpt.tar
logging:
  log_to_screen: true
  log_to_wandb: true
  log_to_file: true
  project: ace
  entity: ai2cm
loader:
  start_indices:
    times:
      - '1980-01-01T00:00:00'
      - '1985-01-01T00:00:00'
      - '1990-01-01T00:00:00'
      - '1995-01-01T00:00:00'
      - '2000-01-01T00:00:00'
      - '2005-01-01T00:00:00'
      - '2010-01-01T00:00:00'
  dataset:
    data_path: /climate-default/2024-06-20-era5-1deg-8layer-1940-2022-netcdfs
  num_data_workers: 4
aggregator:
  log_zonal_mean_images: true
  log_histograms: true
data_writer:
  save_prediction_files: false
  save_monthly_files: false