runs:
  random-CO2-1xCO2-ic_0001: s3://emulators/ai2_colab/2025-11-24-CM4-like-AM4-random-CO2/random-CO2-1xCO2-ic_0001
  random-CO2-2xCO2-ic_0001: s3://emulators/ai2_colab/2025-11-24-CM4-like-AM4-random-CO2/random-CO2-2xCO2-ic_0001
  random-CO2-4xCO2-ic_0001: s3://emulators/ai2_colab/2025-11-24-CM4-like-AM4-random-CO2/random-CO2-4xCO2-ic_0001
  random-CO2-1xCO2-ic_0002: s3://emulators/ai2_colab/2025-11-24-CM4-like-AM4-random-CO2/random-CO2-1xCO2-ic_0002
  random-CO2-2xCO2-ic_0002: s3://emulators/ai2_colab/2025-11-24-CM4-like-AM4-random-CO2/random-CO2-2xCO2-ic_0002
  random-CO2-4xCO2-ic_0002: s3://emulators/ai2_colab/2025-11-24-CM4-like-AM4-random-CO2/random-CO2-4xCO2-ic_0002
  random-CO2-1xCO2-ic_0003: s3://emulators/ai2_colab/2025-11-24-CM4-like-AM4-random-CO2/random-CO2-1xCO2-ic_0003
  random-CO2-2xCO2-ic_0003: s3://emulators/ai2_colab/2025-11-24-CM4-like-AM4-random-CO2/random-CO2-2xCO2-ic_0003
  random-CO2-4xCO2-ic_0003: s3://emulators/ai2_colab/2025-11-24-CM4-like-AM4-random-CO2/random-CO2-4xCO2-ic_0003
data_output_directory: gs://leap-scratch/jpdunc23/2025-12-02-CM4-like-AM4-random-CO2-ensemble-sea-ice
dataset_computation:
  ice_zarr: ice_6hourly.zarr
  nc_mosaic_path: s3://emulators/ai2_colab/2024-11-11-static-data/ocean_hgrid.nc
  nc_target_grid_path: s3://emulators/ai2_colab/2024-11-11-static-data/gaussian_grid_180_by_360.nc
  ocean_static:
    zarr: ocean_static.zarr
    names:
    - wet
    - areacello
    renaming:
      xh: x
      yh: y
  outer_chunks:
    time_dim: 360
    latitude_dim: 180
    longitude_dim: 360
n_split: 12
dask:
  n_workers: 16
  use_gateway: true
  cluster_options:
    worker_resource_allocation: "8CPU, 57.9Gi"
    idle_timeout_minutes: 10
filesystem:
  protocol: s3
  storage_options:
    profile: ai2
    client_kwargs:
      endpoint_url: https://nyu1.osn.mghpcc.org
stats:
  output_directory: /dev/null
  start_date: null
  end_date: null
  data_type: CM4
  beaker_dataset: not_used
