version: "2025-10-20"
family_name: cm4-piControl-200yr-no-smoothing-coupled
output_directory: /climate-default

coupled_datasets:
  coupled_ts:
    how: interpolate_sst
  coupled_sea_surface:
    sst_threshold: 291.75
    ocean_extra_masked_names: ["HI", "sea_ice_volume", "UI", "VI", "sfdsi"]
    surface_flux_window_avg:
      window_timedelta: 120h
      first_timestamp: "0151-01-03T12:00:00"
      last_timestamp: "0350-12-29T12:00:00"
      subset_names:
        - DLWRFsfc
        - DSWRFsfc
        - ULWRFsfc
        - USWRFsfc
        - LHTFLsfc
        - SHTFLsfc
        - PRATEsfc
        - eastward_surface_wind_stress
        - northward_surface_wind_stress
        - total_frozen_precipitation_rate
  coupled_sea_ice:
    window_avg:
      window_timedelta: 120h
      first_timestamp: "0151-01-06T00:00:00"
      shift_timestamps_to_avg_interval_midpoint: true
    include_ts: true
  output_writer:
    n_dask_workers: 32

input_datasets:
  climate_data_type: "CM4"
  atmosphere:
    zarr_path: /climate-default/2025-03-21-CM4-piControl-atmosphere-land-1deg-8layer-200yr.zarr
    time_chunk_size: 500
    extra_fields:
      names_and_prefixes: ["ak_", "bk_"]
  sea_ice:
    zarr_path: /climate-default/2025-08-14-cm4-piControl-200yr-sea-ice-6h.zarr
    time_chunk_size: 500
  ocean:
    zarr_path: /climate-default/2025-10-15-cm4-piControl-200yr-ocean-no-smoothing.zarr
    time_chunk_size: 25
    extra_fields:
      names_and_prefixes: ["idepth_", "mask_"]
  stats:
    atmosphere_dir: /climate-default/2025-03-21-CM4-piControl-atmosphere-land-1deg-8layer-200yr-stats/combined
    ocean_dir: /climate-default/2025-10-15-cm4-piControl-200yr-ocean-no-smoothing-stats
