runs:
  2025-04-03-e3smv3-1deg-ramped: None
data_output_directory: /pscratch/sd/r/elynnwu/fme-preprocess/zarr/
stats:
  output_directory: /pscratch/sd/r/elynnwu/fme-dataset/2026-02-03-E3SMv3-AMIP-1970-2020-1deg-8layer
  start_date: "1970-01-01"
  end_date: "2019-12-31"
  data_type: E3SMV2
  beaker_dataset: e3sm-1deg-8layers-stats # this is not used in e3sm data processing

dataset_computation:
  reference_vertical_coordinate_file: None
  time_invariant_dir: /global/cfs/cdirs/m4331/jpduncan/e3smv2/time_invariant
  vertical_coarsening_indices:
# computed here: https://github.com/ai2cm/explore/blob/master/jamesd/2023-06-09-e3smv2-vertical-interface-indices.ipynb
#[np.int64(0), np.int64(25), np.int64(38), np.int64(46), np.int64(52), np.int64(56), np.int64(61), np.int64(69), np.int64(80)]
    - [0, 25]
    - [25, 38]
    - [38, 46]
    - [46, 52]
    - [52, 56]
    - [56, 61]
    - [61, 69]
    - [69, 80]
  roundtrip_fraction_kept: 1.0
  roundtrip_variables:
    - PS
    - TS
    - T
    - U
    - V
    - Q
    - CLDLIQ
    - CLDICE
    - RAINQM
    - TMQ
    - TGCLDLWP
    - TGCLDIWP
    - QREFHT
    - TREFHT
    - U10
  n_split: 200
  CO2_concentration: 0.0003887
  variable_sources:
    time_invariant:
      - PHIS
    6hourly_instant/1yr:
      - PS
      - TS
      - T
      - U
      - V
      - Q
      - CLDLIQ
      - CLDICE
      - RAINQM
      - TMQ
      - TGCLDLWP
      - TGCLDIWP
      - OCNFRAC
      - LANDFRAC
      - ICEFRAC
      - QREFHT
      - TREFHT
      - U10
    6hourly/1yr:
      - PRECT
      - LHFLX
      - SHFLX
      - FLNS
      - FLDS
      - FSNS
      - FSDS
      - FSNTOA
      - SOLIN
      - FLUT
      - PRECSC
      - PRECSL
      - QFLX
  renaming:
    PS: PRESsfc
    LHFLX: LHTFLsfc
    SHFLX: SHTFLsfc
    surface_precipitation_rate: PRATEsfc
    FSDS: DSWRFsfc
    surface_upward_shortwave_flux: USWRFsfc
    FLDS: DLWRFsfc
    surface_upward_longwave_flux: ULWRFsfc
    FLUT: ULWRFtoa
    SOLIN: DSWRFtoa
    top_of_atmos_upward_shortwave_flux: USWRFtoa
    T_0: air_temperature_0
    T_1: air_temperature_1
    T_2: air_temperature_2
    T_3: air_temperature_3
    T_4: air_temperature_4
    T_5: air_temperature_5
    T_6: air_temperature_6
    T_7: air_temperature_7
    LANDFRAC: land_fraction
    OCNFRAC: ocean_fraction
    ICEFRAC: sea_ice_fraction
    TS: surface_temperature
    U_0: eastward_wind_0
    U_1: eastward_wind_1
    U_2: eastward_wind_2
    U_3: eastward_wind_3
    U_4: eastward_wind_4
    U_5: eastward_wind_5
    U_6: eastward_wind_6
    U_7: eastward_wind_7
    V_0: northward_wind_0
    V_1: northward_wind_1
    V_2: northward_wind_2
    V_3: northward_wind_3
    V_4: northward_wind_4
    V_5: northward_wind_5
    V_6: northward_wind_6
    V_7: northward_wind_7
    QREFHT: Q2m
    TREFHT: TMP2m
    U10: wind_speed_10m
  standard_names:
    total_frozen_precip_rate: None
    surface_snow_rate: PRECSL
    surface_ice_rate: PRECSC
    surface_graupel_rate: None
    longitude_dim: lon
    latitude_dim: lat
    vertical_dim: lev
    vertical_interface_dim: ilev
    time_dim: time
    surface_pressure: PS
    latent_heat_flux: LHFLX
    precip_rate: PRECT
    precipitable_water_path: precipitable_water_path
    pressure_thickness: pressure_thickness_of_atmospheric_layer
    air_temperature: T
    specific_humidity: Q
    cloud_water_mixing_ratio: CLDLIQ
    cloud_ice_mixing_ratio: CLDICE
    graupel_mixing_ratio: None
    rain_mixing_ratio: RAINQM
    snow_mixing_ratio: None
    northward_wind: V
    eastward_wind: U
    hybrid_level_coeffs:
      - hyai
      - hybi