runs:
  2026-02-12-X-SHiELD-AMIP-plus-4K-1deg-8layer-1yr: gs://vcm-ml-raw-flexible-retention/2026-02-09-X-SHiELD-AMIP-plus-4K-FME/regridded-zarrs/gaussian_grid_180_by_360/plus-4K
data_output_directory: gs://vcm-ml-intermediate
stats:
  output_directory: gs://vcm-ml-intermediate/2026-02-12-X-SHiELD-AMIP-plus-4K-1deg-8layer-1yr-stats
  beaker_dataset: 2026-02-12-X-SHiELD-AMIP-plus-4K-1deg-8layer-1yr-stats
  start_date: "2020-01-01T06:00:00"  # Ignore first roughly 2.5 months as spin-up.
  end_date: "2021-01-01T00:00:00"  # Span exactly 1 year (note datetime string indexing is inclusive).
  data_type: FV3GFS
dataset_computation:
  reference_vertical_coordinate_file: gs://vcm-ml-raw-flexible-retention/2024-03-10-C96-SHiELD-FME-reference/vertical-coordinate-file/fv_core.res.nc
  vertical_coarsening_indices:
    - [0, 11]
    - [11, 21]
    - [21, 30]
    - [30, 39]
    - [39, 49]
    - [49, 58]
    - [58, 67]
    - [67, 79]
  renaming:
    specific_humidity_at_two_meters: Q2m
    air_temperature_at_two_meters: TMP2m
    eastward_wind_at_ten_meters: UGRD10m
    northward_wind_at_ten_meters: VGRD10m
  variable_sources:
    fluxes_2d.zarr:
      - PRATEsfc
      - LHTFLsfc
      - SHTFLsfc
      - DLWRFsfc
      - DSWRFsfc
      - DSWRFtoa
      - ULWRFsfc
      - ULWRFtoa
      - USWRFsfc
      - USWRFtoa
      - GRAUPELsfc
      - ICEsfc
      - SNOWsfc
    column_integrated_dynamical_fields.zarr:
      - precipitable_water_path
      - PRESsfc
    air_temperature.zarr:
      - air_temperature
    eastward_wind.zarr:
      - eastward_wind
    northward_wind.zarr:
      - northward_wind
    specific_humidity.zarr:
      - specific_humidity
    cloud_water_mixing_ratio.zarr:
      - cloud_water_mixing_ratio
    cloud_ice_mixing_ratio.zarr:
      - cloud_ice_mixing_ratio
    rain_mixing_ratio.zarr:
      - rain_mixing_ratio
    snow_mixing_ratio.zarr:
      - snow_mixing_ratio
    graupel_mixing_ratio.zarr:
      - graupel_mixing_ratio
    pressure_thickness_of_atmospheric_layer.zarr:
      - pressure_thickness_of_atmospheric_layer
    instantaneous_physics_fields.zarr:
      - air_temperature_at_two_meters
      - eastward_wind_at_ten_meters
      - northward_wind_at_ten_meters
      - surface_temperature
      - soil_moisture_0
      - soil_moisture_1
      - soil_moisture_2
      - soil_moisture_3
      - land_fraction
      - ocean_fraction
      - sea_ice_fraction
      - snow_cover_fraction
      - specific_humidity_at_two_meters
    pressure_interpolated_fields.zarr:
      - RH200
      - RH500
      - RH850
      - TMP200
      - TMP500
      - TMP850
      - UGRD200
      - UGRD500
      - UGRD850
      - UGRD1000
      - VGRD200
      - VGRD500
      - VGRD850
      - VGRD1000
      - h50
      - h500
      - h850
      - h1000
    static.zarr:
      - HGTsfc
    scalar.zarr:
      - global_mean_co2
  standard_names:
    total_frozen_precip_rate: None
