experiment_dir: /results
n_forward_steps: 14600
forward_steps_in_memory: 50
checkpoint_path: /ckpt.tar
logging:
  log_to_screen: true
  log_to_wandb: true
  log_to_file: true
  project: ace
  entity: ai2cm
loader:
  start_indices:
    first: 0
    n_initial_conditions: 1
  dataset:
    data_path: /climate-default/2024-06-20-era5-1deg-8layer-1940-2022-netcdfs
  num_data_workers: 4
data_writer:
  save_prediction_files: false
  save_monthly_files: false
