experiment_dir: /results
n_forward_steps: 58300
forward_steps_in_memory: 50
checkpoint_path: /ckpt.tar
logging:
  log_to_screen: true
  log_to_wandb: true
  log_to_file: true
  project: ace
  entity: ai2cm
loader:
  start_indices:
    times:
     - '0311-01-01T06:00:00'
  dataset:
    data_path: /climate-default/2024-11-15-CM4-piControl-atmosphere-1deg-8layer-200yr/netCDFs/ic_0001
  num_data_workers: 4
aggregator:
  log_zonal_mean_images: false
data_writer:
  save_prediction_files: false
  save_monthly_files: false