experiment_dir: /results
save_checkpoint: true
validate_using_ema: true
ema:
  decay: 0.999
max_epochs: 120
n_forward_steps: 4
inference:
  n_forward_steps: 1440
  forward_steps_in_memory: 40
  loader:
    start_indices:
      times:
      - '0151-01-06T00:00:00'
      - '0171-01-06T00:00:00'
      - '0191-01-06T00:00:00'
      - '0211-01-06T00:00:00'
      - '0231-01-06T00:00:00'
      - '0251-01-06T00:00:00'
      - '0271-01-06T00:00:00'
      - '0291-01-06T00:00:00'
    dataset:
      ocean:
        data_path: /climate-default
        file_pattern: 2025-04-16-cm4-piControl-ocean-200yr-dataset.zarr
        engine: zarr
      atmosphere:
        data_path: /climate-default/2025-01-27-cm4-piControl-atmosphere-5daily-sfc-only/zarr_v3
        file_pattern: data.zarr
        engine: zarr
      mask_2d:
        data_path: /climate-default/2025-04-16-cm4-piControl-ocean-200yr-dataset
        file_pattern: mask_2d.nc
    num_data_workers: 8
  aggregator:
    log_histograms: false
logging:
  log_to_screen: true
  log_to_wandb: true
  log_to_file: true
  project: ace-samudra-cm4
  entity: ai2cm
train_loader:
  batch_size: 16
  num_data_workers: 8
  dataset:
    ocean:
    - data_path: /climate-default
      file_pattern: 2025-04-16-cm4-piControl-ocean-200yr-dataset.zarr
      engine: zarr
      subset:
        stop_time: '0306-01-01'
    atmosphere:
    - data_path: /climate-default/2025-01-27-cm4-piControl-atmosphere-5daily-sfc-only/zarr_v3
      file_pattern: data.zarr
      engine: zarr
      subset:
        stop_time: '0306-01-01'
    masks:
    - data_path: /climate-default/2025-04-16-cm4-piControl-ocean-200yr-dataset
      file_pattern: mask_2d.nc
      subset:
        stop_time: '0306-01-01'
validation_loader:
  batch_size: 16
  num_data_workers: 8
  dataset:
    ocean:
    - data_path: /climate-default
      file_pattern: 2025-04-16-cm4-piControl-ocean-200yr-dataset.zarr
      engine: zarr
      subset:
        start_time: '0306-01-01'
        stop_time: '0311-01-01'
    atmosphere:
    - data_path: /climate-default/2025-01-27-cm4-piControl-atmosphere-5daily-sfc-only/zarr_v3
      file_pattern: data.zarr
      engine: zarr
      subset:
        start_time: '0306-01-01'
        stop_time: '0311-01-01'
    masks:
    - data_path: /climate-default/2025-04-16-cm4-piControl-ocean-200yr-dataset
      file_pattern: mask_2d.nc
      subset:
        start_time: '0306-01-01'
        stop_time: '0311-01-01'
optimization:
  use_gradient_accumulation: true
  enable_automatic_mixed_precision: false
  lr: 0.0001
  optimizer_type: FusedAdam
  kwargs:
    weight_decay: 0.01
stepper:
  loss:
    type: MSE
  input_masking:
    mask_value: 0
    fill_value: 0.0
    exclude_names_and_prefixes:
      - land_fraction
      - sea_surface_fraction
      - DLWRFsfc
      - DSWRFsfc
      - ULWRFsfc
      - USWRFsfc
      - LHTFLsfc
      - SHTFLsfc
      - PRATEsfc
      - eastward_surface_wind_stress
      - northward_surface_wind_stress
  step:
    type: single_module
    config:
      builder:
        type: Samudra
        config:
          ch_width:
          - 200
          - 250
          - 300
          - 400
          dilation:
          - 1
          - 2
          - 4
          - 8
          n_layers:
          - 1
          - 1
          - 1
          - 1
          norm: instance
      normalization:
        network:
          global_means_path: /statsdata/centering.nc
          global_stds_path: /statsdata/scaling-full-field.nc
      corrector:
        type: ocean_corrector
        config:
          force_positive_names:
          - so_0
          - so_1
          - so_2
          - so_3
          - so_4
          - so_5
          - so_6
          - so_7
          - so_8
          - so_9
          - so_10
          - so_11
          - so_12
          - so_13
          - so_14
          - so_15
          - so_16
          - so_17
          - so_18
          - HI
          sea_ice_fraction_correction:
            sea_ice_fraction_name: sea_ice_fraction
            land_fraction_name: land_fraction
            sea_ice_thickness_name: HI
      next_step_forcing_names:
      - DLWRFsfc
      - DSWRFsfc
      - ULWRFsfc
      - USWRFsfc
      - LHTFLsfc
      - SHTFLsfc
      - PRATEsfc
      - eastward_surface_wind_stress
      - northward_surface_wind_stress
      in_names:
      - DLWRFsfc
      - DSWRFsfc
      - ULWRFsfc
      - USWRFsfc
      - LHTFLsfc
      - SHTFLsfc
      - PRATEsfc
      - eastward_surface_wind_stress
      - northward_surface_wind_stress
      - land_fraction
      - sst
      - zos
      - so_0
      - so_1
      - so_2
      - so_3
      - so_4
      - so_5
      - so_6
      - so_7
      - so_8
      - so_9
      - so_10
      - so_11
      - so_12
      - so_13
      - so_14
      - so_15
      - so_16
      - so_17
      - so_18
      - thetao_0
      - thetao_1
      - thetao_2
      - thetao_3
      - thetao_4
      - thetao_5
      - thetao_6
      - thetao_7
      - thetao_8
      - thetao_9
      - thetao_10
      - thetao_11
      - thetao_12
      - thetao_13
      - thetao_14
      - thetao_15
      - thetao_16
      - thetao_17
      - thetao_18
      - uo_0
      - uo_1
      - uo_2
      - uo_3
      - uo_4
      - uo_5
      - uo_6
      - uo_7
      - uo_8
      - uo_9
      - uo_10
      - uo_11
      - uo_12
      - uo_13
      - uo_14
      - uo_15
      - uo_16
      - uo_17
      - uo_18
      - vo_0
      - vo_1
      - vo_2
      - vo_3
      - vo_4
      - vo_5
      - vo_6
      - vo_7
      - vo_8
      - vo_9
      - vo_10
      - vo_11
      - vo_12
      - vo_13
      - vo_14
      - vo_15
      - vo_16
      - vo_17
      - vo_18
      - sea_ice_fraction
      - HI
      out_names:
      - sst
      - zos
      - so_0
      - so_1
      - so_2
      - so_3
      - so_4
      - so_5
      - so_6
      - so_7
      - so_8
      - so_9
      - so_10
      - so_11
      - so_12
      - so_13
      - so_14
      - so_15
      - so_16
      - so_17
      - so_18
      - thetao_0
      - thetao_1
      - thetao_2
      - thetao_3
      - thetao_4
      - thetao_5
      - thetao_6
      - thetao_7
      - thetao_8
      - thetao_9
      - thetao_10
      - thetao_11
      - thetao_12
      - thetao_13
      - thetao_14
      - thetao_15
      - thetao_16
      - thetao_17
      - thetao_18
      - uo_0
      - uo_1
      - uo_2
      - uo_3
      - uo_4
      - uo_5
      - uo_6
      - uo_7
      - uo_8
      - uo_9
      - uo_10
      - uo_11
      - uo_12
      - uo_13
      - uo_14
      - uo_15
      - uo_16
      - uo_17
      - uo_18
      - vo_0
      - vo_1
      - vo_2
      - vo_3
      - vo_4
      - vo_5
      - vo_6
      - vo_7
      - vo_8
      - vo_9
      - vo_10
      - vo_11
      - vo_12
      - vo_13
      - vo_14
      - vo_15
      - vo_16
      - vo_17
      - vo_18
      - sea_ice_fraction
      - HI
