experiment_dir: /results
n_forward_steps: 730
forward_steps_in_memory: 40
checkpoint_path: /ckpt.tar
logging:
  log_to_screen: true
  log_to_wandb: true
  log_to_file: true
  project: ace
  entity: ai2cm
loader:
  start_indices:
    times:
    - '0311-01-03T12:00:00'
  dataset:
    merge:
    - data_path: /climate-default
      file_pattern: 2025-08-22-cm4-piControl-200yr-coupled-ocean.zarr
      engine: zarr
    - data_path: /climate-default
      file_pattern: 2025-08-07-cm4-piControl-200yr-ocean.zarr
      engine: zarr
    - data_path: /climate-default
      file_pattern: 2025-08-07-cm4-piControl-200yr-5daily-sfc-flux.zarr
      engine: zarr
  num_data_workers: 1
data_writer:
  save_prediction_files: false
  save_monthly_files: true
aggregator:
  log_histograms: true
