# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: gitlab-master.nvidia.com:5005/earth-2/fcn-mip:23.02.27

lint:
  tags:
    - type/docker
    - os/linux
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  before_script:
    - pip install pre-commit
    - pip install external/torch_sht
    - pip install external/modulus-core
    - pip install -e .
    - cp config/ci.py config.py
    - cat config.py
  script:
    - make lint
    - make unit_test
    - coverage report --omit 'test_*.py'

pages:
  image: python:3.10
  only:
    - main
  tags:
    - pages
  before_script:
    - apt-get update
    - apt-get install git-lfs
  script:
    - git lfs pull public
  artifacts:
    paths:
    - public
