gfno_26ch_sc3_layers8_tt64:
    N_grid_channels: 0
    add_grid: false
    add_noise: false
    amp_mode: none
    append_skip: true
    batch_size: 1
    best_checkpoint_path: /runs/gfno_26ch_sc3_layers8_tt64/ngpu64_mp1_sp1/training_checkpoints/best_ckpt_mp{mp_rank}.tar
    checkpoint_path: /runs/gfno_26ch_sc3_layers8_tt64/ngpu64_mp1_sp1/training_checkpoints/ckpt_mp{mp_rank}.tar
    checkpointing: false
    compression: tt
    crop_size_x: null
    crop_size_y: null
    cuda_graph_mode: fwdbwd
    disable_ddp: false
    dt: 1
    embed_dim: 128
    enable_benchy: false
    enable_nhwc: false
    enable_synthetic_data: false
    epsilon_factor: 0
    exp_dir: /runs
    experiment_dir: /runs/gfno_26ch_sc3_layers8_tt64/ngpu64_mp1_sp1
    finetune: false
    global_batch_size: 64
    global_means_path: /stats/global_means.npy
    global_stds_path: /stats/global_stds.npy
    gridtype: sinusoidal
    hard_thresholding_fraction: 1.0
    ics_type: specify_number
    in_channels:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    jit_mode: none
    log_to_screen: true
    log_to_wandb: true
    log_video: 5
    loss: geometric l2
    lr_warmup_steps: 0
    masked_acc: false
    maskpath: null
    matmul_parallel_size: 1
    max_epochs: 300
    max_path: /stats/maxs.npy
    min_path: /stats/mins.npy
    model_parallel_size: 1
    model_parallel_stride: 1
    multistep_count: 1
    multistep_pipeline: false
    n_future: 0
    n_history: 0
    n_initial_conditions: 5
    nettype: fno
    normalization: zscore
    normalization_layer: instance_norm
    num_blocks: 8
    num_data_workers: 4
    num_layers: 8
    optimizer_type: FusedAdam
    orography: false
    orography_path: null
    out_channels:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    parameters_reduction_buffer_count: 1
    perturb: false
    prediction_length: 35
    prediction_type: iterative
    print_timings_frequency: -1
    rank: 64
    resuming: true
    roll: false
    save_channel: false
    save_checkpoint: true
    save_raw_forecasts: true
    scale_factor: 3
    scheduler: CosineAnnealingLR
    scheduler_T_max: 150
    spatial_parallel_size: 1
    spectral_transform: sht
    split_data_channels: false
    target: default
    time_means_path: /stats/time_means.npy
    train_data_path: /train
    use_mlp: true
    valid_autoreg_steps: 20
    valid_data_path: /test
    verbose: false
    wandb_api_key: 02616d14aede6f7c930ac5dd12666bfec8a1b19f
    wandb_entity: bbonev
    wandb_group: era5_windgfno_26ch_sc3_layers8_tt64
    wandb_name: gfno_26ch_sc3_layers8_tt64_ngpu64_mp1_sp1
    wandb_project: euclid
    wireup_info: mpi
    wireup_store: tcp
    world_size: 64
