experiment_dir: /will/be/overwritten
# interpolate model
model:
  mode: "place_holder"
  downscale_factor: -1
  in_names:
    - "place"
    - "holder"
  out_names:
    - "place"
    - "holder"
# checkpoint model
# model:
#   checkpoint: /will/be/overwritten
data:
  fine:
    - data_path: /will/be/overwritten
  coarse:
    - data_path: /will/be/overwritten
  batch_size: 2
  num_data_workers: 2
  strict_ensemble: False
logging:
  log_to_screen: true
  log_to_wandb: true
  log_to_file: true
  project: ace-downscaling
  entity: ai2cm
