experiment_dir: /will/be/overwritten
max_epochs: 2
logging:
  log_to_screen: true
  log_to_wandb: true
  log_to_file: true
  project: ace-downscaling
  entity: ai2cm
optimization:
  lr: 0.0001
train_data:
  path_fine: /will/be/overwritten
  path_coarse: /will/be/overwritten
  data_type: "xarray"
  batch_size: 2
  num_data_workers: 2
validation_data:
  path_fine: /will/be/overwritten
  path_coarse: /will/be/overwritten
  data_type: "xarray"
  batch_size: 2
  num_data_workers: 2
model:
  loss:
    type: "L1"
  module:
    type: swinir
    config:
      depths: [1]
      window_size: 2
      embed_dim: 1
      num_heads: [1]
  normalization:
    fine:
      global_means_path: /will/be/overwritten
      global_stds_path: /will/be/overwritten
    coarse:
      global_means_path: /will/be/overwritten
      global_stds_path: /will/be/overwritten
  in_names:
    - "x"
    - "y"
  out_names:
    - "x"
    - "y"
  use_fine_topography: False
