experiment_dir: /results
n_coupled_steps: 140
coupled_steps_in_memory: 20
checkpoint_path: /ckpt.tar
data_writer:
  ocean:
    save_prediction_files: false
    save_monthly_files: true
  atmosphere:
    save_prediction_files: false
    save_monthly_files: true
forcing_loader:
  atmosphere:
    dataset:
      data_path: /climate-default/2025-08-29-coupled-inference-no-target-data-example/CM4
      file_pattern: cm4-atmosphere-forcing-1yr.zarr
      engine: zarr
      n_repeats: 3
  num_data_workers: 1
initial_condition:
  ocean:
    path: /climate-default/2025-08-29-coupled-inference-no-target-data-example/CM4/cm4-ocean-ic.nc
  atmosphere:
    path: /climate-default/2025-08-29-coupled-inference-no-target-data-example/CM4/cm4-atmosphere-ic.nc
  start_indices:
    first: 0
    n_initial_conditions: 2
logging:
  log_to_screen: true
  log_to_wandb: true
  log_to_file: true
  project: coupled-emulator
  entity: ai2cm